name: flutter_sample_oauth
description: How to implement oauth with Flutter
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # A powerful Http client for Dart, which supports Interceptors, FormData, Request Cancellation,
  # File Downloading, Timeout etc.
  dio: ^3.0.7

  # Flutter plugin for reading and writing
  shared_preferences: ^0.5.5

  # Flutter widgets that make it easy to implement the BLoC design pattern.
  flutter_bloc: ^2.1.1

  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation
  # and to access the concrete implementation from everywhere in your App
  get_it: ^3.0.3

  # The Font Awesome Icon pack
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Automatically generate code for converting to and from JSON by Dart classes.
  json_serializable: ^3.2.3

  # Tools to write binaries that run builders.
  build_runner: ^1.7.2

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/image_header.png
